name: Release to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to release to'
        type: choice
        required: true
        default: 'staging' # Default value, change as needed
        options:
          - 'staging'
          - 'prod'
          - 'mock'
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main' # Default value, change as needed
        type: choice
        options:
          - 'main'
          - 'master'
          - 'release/prod'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Determine Environment
        id: determine_environment
        #run: echo "::set-output name=environment::${{ github.event.inputs.environment }}"
        run: echo "environment=${{ inputs.environment}}" >> $GITHUB_OUTPUT

      - name: Determine Branch
        id: determine_branch
        run: echo "branch=${{ inputs.branch}}" >> $GITHUB_OUTPUT

  release-with-reusable-flow:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy to Environment
        uses: ./.github/workflows/reusable-flow.yaml
        with:
            environment: ${{ inputs.environment}}
            branch: ${{ inputs.branch}}
